apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mumble
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: "mumble"
  replicas: 1 # default, but we want to be explicit.
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mumble
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: murmur
        image: zombi/murmur
        imagePullPolicy: IfNotPresent
        command:
        - /usr/bin/murmurd
        - -fg
        - -ini
        - /config/murmur.ini
        ports:
        - name: control
          containerPort: 64738
          protocol: TCP
        - name: voice
          containerPort: 64738
          protocol: UDP
        volumeMounts:
        - name: {{ .Release.Name }}-mumble
          mountPath: /var/lib/mumble
        - name: tls
          mountPath: /tls
        - name: config
          mountPath: /config
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            memory: 100Mi
      securityContext:
        fsGroup: 2000
      volumes:
      - name: tls
        secret:
          secretName: {{ .Values.domain }}-cert
      - name: config
        configMap:
          name: mumble-config
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-mumble
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
